replicaCount: 1

image:
  repository: gotify/server-arm64
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to chart appVersion

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: gotify.192-168-178-31.sslip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: gotify.192-168-178-31.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  requests:
    memory: "32Mi"
    cpu: "1m"
  limits:
    memory: "128Mi"
    cpu: "10m"

nodeSelector: {}

tolerations: []

affinity: {}

volumes:
  dataPath: ""

defaultUser:
  name: ""
  pass: ""
  passSecret: {}
timezone: ""  # Defaults to 'Europe/Berlin'
