replicaCount: 1

image:
  repository: gotify/server
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to chart appVersion

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: gotify.192-168-178-31.sslip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  requests:
    memory: "32Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "500m"

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  annotations: {}
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 250Mi

defaultUser:
  name: ""
  pass: ""
  passSecret: {}
timezone: ""  # Defaults to 'Europe/Berlin'
