apiVersion: v2
name: ntfy
description: A simple HTTP-based pub-sub notification service
type: application
version: 0.1.0
# renovate: image=binwiederhier/ntfy
appVersion: "v2.14"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
