windmill:
  windmill:
    databaseUrl: postgres://test:$(DATABASE_PASSWORD)@cnpg-cluster-rw/test

    workerGroups:
      - name: "default"
        controller: "Deployment"
        replicas: 1
        privileged: false
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 11319
          runAsGroup: 11319
          fsGroup: 11319
          seccompProfile:
            type: RuntimeDefault
        containerSecurityContext:
          capabilities:
            drop:
              - ALL
          privileged: true
        extraEnv:
          - name: ENABLE_UNSHARE_PID
            value: "true"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test
                key: password
        mode: "worker"
        exposeHostDocker: false
      - name: "custom"
        controller: "Deployment"
        replicas: 1
        privileged: false
        podSecurityContext:
          seccompProfile:
            type: RuntimeDefault
        containerSecurityContext:
          capabilities:
            drop:
              - ALL
          privileged: true
        resources:
          limits:
            memory: "2Gi"
        extraEnv:
          - name: ENABLE_UNSHARE_PID
            value: "true"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test
                key: password
          - name: "INIT_SCRIPT"
            value: "apt-get update\napt-get install -y postgresql-common\n/usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y\napt-get install -y postgresql-client-18"
          - name: "WORKER_TAGS"
            value: "bun,deno,python3,bash,dependency,flow,hub,psql,pg_dump,other"
        mode: "worker"
        exposeHostDocker: false
      - name: "native"
        controller: "Deployment"
        replicas: 1
        privileged: false
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 11319
          runAsGroup: 11319
          fsGroup: 11319
          seccompProfile:
            type: RuntimeDefault
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
        resources:
          limits:
            memory: "2Gi"
        extraEnv:
          - name: "NATIVE_MODE"
            value: "true"
          - name: "SLEEP_QUEUE"
            value: "200"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test
                key: password
        mode: "worker"
        exposeHostDocker: false

    app:
      extraEnv:
      - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: test
            key: password
