apiVersion: v2
name: jellyfin
description: The Free Software Media System
type: application
version: 0.1.0
# renovate: image=jellyfin/jellyfin
appVersion: "10.8.11"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
