replicaCount: 1

image:
  repository: jellyfin/jellyfin
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to chart appVersion

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: jellyfin.192-168-178-31.sslip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  requests:
    memory: "128Mi"
    cpu: "150m"
  limits:
    memory: "1024Mi"
    cpu: "1500m"

nodeSelector: {}

tolerations: []

affinity: {}

enableDLNA: false

volumes:
  configPath: ""
  mediaPaths: []
