apiVersion: v2
name: syncthing
type: application
version: 0.1.4
# renovate: image=syncthing/syncthing
appVersion: "2.0.16"
dependencies:
  - name: common
    version: 0.1.4
    repository: oci://ghcr.io/egvimo/charts
