replicaCount: 1

image:
  repository: syncthing/syncthing
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to chart appVersion

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  requests:
    memory: "128Mi"
    cpu: "5m"
  limits:
    memory: "512Mi"
    cpu: "25m"

nodeSelector: {}

tolerations: []

affinity: {}

volumes:
  syncPath: ""
