authelia:
  ingress:
    enabled: true
    traefikCRD:
      enabled: true
      disableIngressRoute: true

  pod:
    kind: Deployment
    extraVolumeMounts:
      - name: users
        mountPath: /config/users_database.yml
        subPath: users_database.yml
        readOnly: true
    extraVolumes:
      - name: users
        configMap:
          name: authelia-users-database

  configMap:
    theme: dark
    identity_validation:
      reset_password:
        secret:
          value: ''
    authentication_backend:
      file:
        enabled: true
        password:
          algorithm: bcrypt
    access_control:
      rules: []
    session:
      inactivity: 1h
      expiration: 1d
      encryption_key:
        value: ''
      cookies:
        - domain: 192-168-178-31.sslip.io
          subdomain: auth
    storage:
      encryption_key:
        value: ''
      local:
        enabled: true
    notifier:
      filesystem:
        enabled: true
    identity_providers:
      oidc:
        enabled: true
        hmac_secret:
          value: ''
        jwks: []
        clients: []

  persistence:
    enabled: true

users: {}
