apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "windmill.serviceAccountName" (dict "Values" .Values.windmill "Release" .Release "Chart" .Chart) }}-job-runner
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
