{{- include "common.daemonset" (list . "apt-exporter.daemonset") -}}
{{- define "apt-exporter.daemonset" -}}
spec:
  template:
    spec:
      containers:
        - env:
            - name: APT_ROOT_DIR
              value: /host
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: host
              mountPath: /host
              mountPropagation: HostToContainer
              readOnly: true
          {{- include "common.container" . | nindent 10 }}
      volumes:
        - name: host
          hostPath:
            path: /
{{- end -}}
