apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  {{- include "common.storageClass" . | nindent 2 }}
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
