apiVersion: 1
groups:
  - orgId: 1
    name: Longhorn
    folder: Alerts
    interval: 1m
    rules:
      - uid: longhorn-volume-space-warning
        title: Longhorn Volume Actual Space Used Warning
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: (longhorn_volume_actual_size_bytes / longhorn_volume_capacity_bytes) * 100 > 90
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: The actual used space of Longhorn volume is over 90% of the capacity.
          description: 'The actual space used by Longhorn volume {{ $labels.volume }} on {{ $labels.node }} is at {{ $value }}% capacity for more than 5 minutes.'
        labels:
          severity: warning
          receiver: apprise
        isPaused: false

      - uid: longhorn-volume-status-critical
        title: Longhorn Volume Status Critical
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: longhorn_volume_robustness == 3
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: Longhorn volume {{ $labels.volume }} is Fault
          description: 'Longhorn volume {{ $labels.volume }} on {{ $labels.node }} is Fault for more than 2 minutes.'
        labels:
          severity: critical
          receiver: apprise
        isPaused: false

      - uid: longhorn-volume-status
        title: Longhorn Volume Status
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: longhorn_volume_robustness > 1
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: Longhorn volume {{ $labels.volume }} is not healthy
          description: 'Longhorn volume {{ $labels.volume }} on node {{ $labels.node }} has status {{ $labels.robustness }}.'
        labels:
          severity: warning
          receiver: apprise
        isPaused: false

      - uid: longhorn-node-storage-warning
        title: Longhorn Node Storage Warning
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: ((longhorn_node_storage_usage_bytes + longhorn_node_storage_reservation_bytes) / longhorn_node_storage_capacity_bytes) * 100 > 75
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: The used storage of node is over 70% of the capacity.
          description: 'The used storage of node {{ $labels.node }} is at {{ $value }}% capacity for more than 5 minutes.'
        labels:
          severity: warning
          receiver: apprise
        isPaused: false

      - uid: longhorn-node-down
        title: Longhorn Node Down
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: (avg(longhorn_node_count_total) or on() vector(0)) - (count(longhorn_node_status{condition="ready"} == 1) or on() vector(0)) > 0
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: Longhorn nodes offline
          description: 'There are {{ $value }} Longhorn nodes which have been offline.'
        labels:
          severity: critical
          receiver: apprise
        isPaused: false
