apiVersion: 1
groups:
  - orgId: 1
    name: Node
    folder: Alerts
    interval: 1m
    rules:
      - uid: node-temperature
        title: Node Temperature
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: max by(instance) (node_thermal_zone_temp)
              instant: true
              range: false
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              type: reduce
              expression: A
              reducer: last
              refId: B
          - refId: C
            datasourceUid: __expr__
            model:
              type: threshold
              expression: B
              refId: C
              conditions:
                - type: query
                  query:
                    params:
                      - C
                  reducer:
                    type: last
                  evaluator:
                    type: gt
                    params:
                      - 60
        noDataState: OK
        execErrState: Error
        for: 10m
        annotations:
          summary: Node temperature warning
          description: 'Node {{ $labels.instance }} temperature above 60°C'
        labels:
          severity: warning
          receiver: apprise
        isPaused: false

      - uid: update-available
        title: Update Available
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 900
              to: 0
            datasourceUid: prometheus
            model:
              expr: last_over_time(file_exists{file=~"/.*/dietpi/.*"}[1h]) != 0
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 15m
        annotations:
          summary: System update available
          description: 'Update for {{ $labels.instance }} available'
        labels:
          severity: info
          receiver: apprise
        isPaused: false
