apiVersion: 1
groups:
  - orgId: 1
    name: Pod
    folder: Alerts
    interval: 1m
    rules:
      - uid: pod-unhealthy
        title: Pod Unhealthy
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: sum by(namespace, pod, phase) (kube_pod_status_phase{phase=~"Failed|Pending|Unknown"}) > 0
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: Kubernetes Pod unhealthy
          description: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} is in phase {{ $labels.phase }}'
        labels:
          severity: warning
          receiver: gotify
        isPaused: false

      - uid: pod-crash-looping
        title: Pod CrashLoopBackOff
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"}[5m]) > 0
              format: table
              range: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 2m
        annotations:
          summary: Kubernetes Pod crash looping
          description: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping'
        labels:
          severity: critical
          receiver: gotify
        isPaused: false
