apiVersion: 1
groups:
  - orgId: 1
    name: rules
    folder: alerts
    interval: 1m
    rules:
      - uid: node-temperature
        title: Node Temperature
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: max_over_time(node_thermal_zone_temp[5m]) > 60
              format: table
              range: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 10m
        annotations:
          summary: Node temperature warning
          description: 'Node {{ $labels.instance }} temperature above 60°C'
        labels:
          severity: warning
          receiver: gotify
        isPaused: false

      - uid: argo-cd-app-sync
        title: Argo CD App Out of Sync
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: argocd_app_info{sync_status!="Synced"} != 0
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: Argo CD app not synced
          description: 'Argo CD application {{ $labels.name }} is out of sync'
        labels:
          severity: warning
          receiver: gotify
        isPaused: false

      - uid: argo-cd-app-health
        title: Argo CD App Unhealthy
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: argocd_app_info{health_status!="Healthy"} != 0
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: Argo CD app not healthy
          description: 'Argo CD application {{ $labels.name }} is not healthy (status={{ $labels.health_status }})'
        labels:
          severity: critical
          receiver: gotify
        isPaused: false

      - uid: pod-unhealthy
        title: Pod Unhealthy
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: sum by(namespace, pod, phase) (kube_pod_status_phase{phase=~"Failed|Pending|Unknown"}) > 0
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: Kubernetes Pod unhealthy
          description: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} is in phase {{ $labels.phase }}'
        labels:
          severity: warning
          receiver: gotify
        isPaused: false

      - uid: pod-crash-looping
        title: Pod CrashLoopBackOff
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"}[5m]) > 0
              format: table
              range: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 2m
        annotations:
          summary: Kubernetes Pod crash looping
          description: 'Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping'
        labels:
          severity: critical
          receiver: gotify
        isPaused: false

      - uid: update-available
        title: Update Available
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 3600
              to: 0
            datasourceUid: prometheus
            model:
              expr: last_over_time(file_exists{file=~"/.*/dietpi/.*"}[1h]) != 0
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 15m
        annotations:
          summary: System update available
          description: 'Update for {{ $labels.instance }} available'
        labels:
          severity: info
          receiver: gotify
        isPaused: false

      - uid: longhorn-volume-space-warning
        title: Longhorn Volume Actual Space Used Warning
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: (longhorn_volume_actual_size_bytes / longhorn_volume_capacity_bytes) * 100 > 90
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: The actual used space of Longhorn volume is over 90% of the capacity.
          description: The actual space used by Longhorn volume {{ $labels.volume }} on {{ $labels.node }} is at {{ $value }}% capacity for more than 5 minutes.
        labels:
          severity: warning
          receiver: gotify
        isPaused: false

      - uid: longhorn-volume-status-critical
        title: Longhorn Volume Status Critical
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: longhorn_volume_robustness == 3
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: Longhorn volume {{ $labels.volume }} is Fault
          description: Longhorn volume {{ $labels.volume }} on {{ $labels.node }} is Fault for more than 2 minutes.
        labels:
          severity: critical
          receiver: gotify
        isPaused: false

      - uid: longhorn-volume-status
        title: Longhorn Volume Status
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: longhorn_volume_robustness > 1
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: Longhorn volume {{ $labels.volume }} is not healthy
          description: Longhorn volume {{ $labels.volume }} on node {{ $labels.node }} has status {{ $labels.robustness }}.
        labels:
          severity: warning
          receiver: gotify
        isPaused: false

      - uid: longhorn-node-storage-warning
        title: Longhorn Node Storage Warning
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: ((longhorn_node_storage_usage_bytes + longhorn_node_storage_reservation_bytes) / longhorn_node_storage_capacity_bytes) * 100 > 75
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: The used storage of node is over 70% of the capacity.
          description: The used storage of node {{ $labels.node }} is at {{ $value }}% capacity for more than 5 minutes.
        labels:
          severity: warning
          receiver: gotify
        isPaused: false

      - uid: longhorn-node-down
        title: Longhorn Node Down
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: (avg(longhorn_node_count_total) or on() vector(0)) - (count(longhorn_node_status{condition="ready"} == 1) or on() vector(0)) > 0
              format: table
              instant: true
              refId: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: Longhorn nodes offline
          description: There are {{ $value }} Longhorn nodes which have been offline.
        labels:
          severity: critical
          receiver: gotify
        isPaused: false
