apiVersion: 1
groups:
  - orgId: 1
    name: rules
    folder: alerts
    interval: 1m
    rules:
      - uid: argo-cd-app-health
        title: Argo CD app health
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              editorMode: builder
              expr: argocd_app_info{health_status!="Healthy"}
              format: table
              hide: false
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: Health status of Argo CD applications
        labels:
          receiver: gotify
        isPaused: false
