{{- include "common.deployment" (list . "readymedia.deployment") -}}
{{- define "readymedia.deployment" -}}
spec:
  template:
    spec:
      containers:
        - env:
            - name: MINIDLNA_MEDIA_DIR_1
              value: V,/media/video
            - name: MINIDLNA_MEDIA_DIR_2
              value: /media/photo
            - name: MINIDLNA_MEDIA_DIR_3
              value: A,/media/audio
            {{- if .Values.friendlyName }}
            - name: MINIDLNA_FRIENDLY_NAME
              value: {{ .Values.friendlyName | quote }}
            {{- end }}
          volumeMounts:
            - mountPath: /minidlna/cache
              name: cache
            {{- if .Values.volumes.videoPath }}
            - mountPath: /media/video
              name: video
              readOnly: true
            {{- end }}
            {{- if .Values.volumes.photoPath }}
            - mountPath: /media/photo
              name: photo
              readOnly: true
            {{- end }}
            {{- if .Values.volumes.audioPath }}
            - mountPath: /media/audio
              name: audio
              readOnly: true
            {{- end }}
          {{- include "common.container" . | nindent 10 }}
      hostNetwork: true
      volumes:
        - name: cache
          emptyDir: {}
        {{- if .Values.volumes.videoPath }}
        - name: video
          hostPath:
            path: {{ .Values.volumes.videoPath }}
            type: Directory
        {{- end }}
        {{- if .Values.volumes.photoPath }}
        - name: photo
          hostPath:
            path: {{ .Values.volumes.photoPath }}
            type: Directory
        {{- end }}
        {{- if .Values.volumes.audioPath }}
        - name: audio
          hostPath:
            path: {{ .Values.volumes.audioPath }}
            type: Directory
        {{- end }}
{{- end -}}
