apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "readymedia.fullname" . }}
  labels:
    {{- include "readymedia.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "readymedia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "readymedia.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MINIDLNA_MEDIA_DIR
              value: /media
            {{- if .Values.friendlyName }}
            - name: MINIDLNA_FRIENDLY_NAME
              value: {{ .Values.friendlyName | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.mediaPath }}
          volumeMounts:
            - mountPath: /media
              name: media
          {{- end }}
      hostNetwork: true
      {{- if .Values.persistence.mediaPath }}
      volumes:
        - name: media
          hostPath:
            path: {{ .Values.persistence.mediaPath }}
            type: Directory
      {{- end }}
