{{- include "common.deployment" (list . "readymedia.deployment") -}}
{{- define "readymedia.deployment" -}}
spec:
  template:
    spec:
      containers:
        - env:
            - name: MINIDLNA_MEDIA_DIR
              value: /media
            {{- if .Values.friendlyName }}
            - name: MINIDLNA_FRIENDLY_NAME
              value: {{ .Values.friendlyName | quote }}
            {{- end }}
          {{- if .Values.volumes.mediaPath }}
          volumeMounts:
            - mountPath: /media
              name: media
              readOnly: true
          {{- end }}
          {{- include "common.container" . | nindent 10 }}
      hostNetwork: true
      {{- if .Values.volumes.mediaPath }}
      volumes:
        - name: media
          hostPath:
            path: {{ .Values.volumes.mediaPath }}
            type: Directory
      {{- end }}
{{- end -}}
