{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "readymedia.fullname" . }}
  labels:
    {{- include "readymedia.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
  volumeName: {{ include "readymedia.fullname" . }}
{{- end }}
