apiVersion: v2
name: readymedia
description: ReadyMedia (formerly known as MiniDLNA) is a simple media server software
type: application
version: 0.1.0
appVersion: "1.3.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
