replicaCount: 1

image:
  repository: vladgh/minidlna
  pullPolicy: IfNotPresent
  tag: "1.3.4"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  requests:
    memory: "64Mi"
    cpu: "150m"
  limits:
    memory: "256Mi"
    cpu: "1500m"

nodeSelector: {}

tolerations: []

affinity: {}

volumes:
  videoPath: ""
  photoPath: ""
  audioPath: ""

friendlyName: ""
