replicaCount: 1

image:
  repository: vladgh/minidlna
  pullPolicy: IfNotPresent
  tag: "1.2.0"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

volumes:
  mediaPath: ""

friendlyName: ""
