persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

extraVolumes:
  - name: test
    mountPath: /content/test
    hostPath: /tmp
    readOnly: true

enableDLNA: true
