{{- include "common.deployment" (list . "n8n.deployment") -}}
{{- define "n8n.deployment" -}}
spec:
  template:
    spec:
      enableServiceLinks: false
      containers:
        - env:
            - name: GENERIC_TIMEZONE
              value: {{ .Values.timezone | default "Europe/Berlin" | quote }}
            - name: TZ
              value: {{ .Values.timezone | default "Europe/Berlin" | quote }}
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 4
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
          {{- if .Values.volumes.dataPath }}
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: data
            {{- range .Values.extraVolumes }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
              readOnly: {{ .readOnly | default false }}
            {{- end }}
          {{- end }}
          {{- include "common.container" . | nindent 10 }}
      {{- if .Values.volumes.dataPath }}
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.volumes.dataPath }}
            type: Directory
        {{- range .Values.extraVolumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: Directory
        {{- end }}
      {{- end }}
{{- end -}}
