{{- include "common.deployment" (list . "n8n.deployment") -}}
{{- define "n8n.deployment" -}}
spec:
  template:
    spec:
      enableServiceLinks: false
      containers:
        - env:
            - name: GENERIC_TIMEZONE
              value: {{ .Values.timezone | default "Europe/Berlin" | quote }}
            - name: TZ
              value: {{ .Values.timezone | default "Europe/Berlin" | quote }}
            {{- if or .Values.basicAuthUser.name .Values.basicAuthUser.password }}
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            {{- end }}
            {{- if .Values.basicAuthUser.name }}
            - name: N8N_BASIC_AUTH_USER
              value: {{ .Values.basicAuthUser.name | quote }}
            {{- end }}
            {{- if or .Values.basicAuthUser.password .Values.basicAuthUser.passwordSecret }}
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.basicAuthUser.passwordSecret.name | default (include "common.fullname" .) }}
                  key: {{ .Values.basicAuthUser.passwordSecret.key | default "basicAuthUser-password" }}
            {{- end }}
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          {{- if .Values.volumes.dataPath }}
          volumeMounts:
            - mountPath: /root/.n8n
              name: data
            {{- range .Values.extraVolumes }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
              readOnly: {{ .readOnly | default false }}
            {{- end }}
          {{- end }}
          {{- include "common.container" . | nindent 10 }}
      {{- if .Values.volumes.dataPath }}
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.volumes.dataPath }}
            type: Directory
        {{- range .Values.extraVolumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: Directory
        {{- end }}
      {{- end }}
{{- end -}}
