{{- include "common.deployment" (list . "n8n.deployment") -}}
{{- define "n8n.deployment" -}}
spec:
  template:
    spec:
      enableServiceLinks: false
      containers:
        - env:
            - name: GENERIC_TIMEZONE
              value: {{ .Values.timezone | default "Europe/Berlin" | quote }}
            - name: TZ
              value: {{ .Values.timezone | default "Europe/Berlin" | quote }}
            - name: DB_SQLITE_VACUUM_ON_STARTUP
              value: "true"
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 4
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
          volumeMounts:
            - name: data
              mountPath: /.n8n
            - name: cache
              mountPath: /.cache
            {{- range .Values.extraVolumes }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
              readOnly: {{ .readOnly | default false }}
            {{- end }}
          {{- include "common.container" . | nindent 10 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "common.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: cache
          emptyDir: {}
        {{- range .Values.extraVolumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: Directory
        {{- end }}
{{- end -}}
