{{- include "common.daemonset" (list . "file-exporter.daemonset") -}}
{{- define "file-exporter.daemonset" -}}
spec:
  template:
    spec:
      containers:
        - command: ["/exporter"]
          args:
            {{- range .Values.files }}
            - --file
            - {{ . | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: host
              mountPath: /host
              mountPropagation: HostToContainer
              readOnly: true
          {{- include "common.container" . | nindent 10 }}
      volumes:
        - name: host
          hostPath:
            path: /
{{- end -}}
