{{- include "common.deployment" (list . "kibitzr.deployment") -}}
{{- define "kibitzr.deployment" -}}
spec:
  template:
    spec:
      containers:
        - command: ["kibitzr"]
          args: ["run"]
          workingDir: /data
          volumeMounts:
            - mountPath: /data
              name: data
            {{- if .Values.volumes.configPath }}
            - mountPath: /.config/kibitzr
              name: config
              readOnly: true
            {{- end }}
          {{- include "common.container" . | nindent 10 }}
      volumes:
        - name: data
          emptyDir: {}
        {{- if .Values.volumes.configPath }}
        - name: config
          hostPath:
            path: {{ .Values.volumes.configPath }}
            type: Directory
        {{- end }}
{{- end -}}
