{{- include "common.deployment" (list . "kibitzr.deployment") -}}
{{- define "kibitzr.deployment" -}}
{{- $fullName := include "common.fullname" . -}}
spec:
  template:
    spec:
      containers:
        - command: ["kibitzr"]
          args: ["run"]
          workingDir: /working-dir
          {{- if .Values.secrets }}
          env:
            {{- range $key, $value := .Values.secrets }}
            - name: {{ $key | snakecase | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: {{ $key }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: /working-dir
              name: working-dir
            - mountPath: /working-dir/kibitzr.yml
              name: config
              subPath: kibitzr.yml
            {{- if .Values.kibitzrCredsConfig }}
            - mountPath: /working-dir/kibitzr-creds.yml
              name: config
              subPath: kibitzr-creds.yml
            {{- end }}
          {{- include "common.container" . | nindent 10 }}
      volumes:
        - name: working-dir
          emptyDir: {}
        - name: config
          configMap:
            name: {{ $fullName }}
{{- end -}}
