apiVersion: v2
name: s3proxy
type: application
version: 0.1.1
# renovate: image=andrewgaul/s3proxy
appVersion: "3.1.0"
dependencies:
  - name: common
    version: 0.1.3
    repository: oci://ghcr.io/egvimo/charts
