{{- include "common.deployment" (list . "jdownloader.deployment") -}}
{{- define "jdownloader.deployment" -}}
spec:
  template:
    spec:
      containers:
        - env:
            - name: MYJD_DEVICE_NAME
              value: {{ .Values.deviceName | default "Kubernetes" | quote }}
            - name: UMASK
              value: {{ .Values.umask | default "0002" | quote }}
            {{- if and .Values.myJdAccount.email (or .Values.myJdAccount.password .Values.myJdAccount.passwordSecret) }}
            - name: MYJD_USER
              value: {{ .Values.myJdAccount.email | quote }}
            - name: MYJD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.myJdAccount.passwordSecret.name | default (include "common.fullname" .) }}
                  key: {{ .Values.myJdAccount.passwordSecret.key | default "myJdAccount-password" }}
            {{- end }}
          ports:
            - name: direct-conn
              containerPort: 3129
              protocol: TCP
          volumeMounts:
            - name: app
              mountPath: /opt/JDownloader/app
            - name: cfg
              mountPath: /opt/JDownloader/app/cfg
            {{- range .Values.extraVolumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly | default false }}
            {{- end }}
          {{- include "common.container" . | nindent 10 }}
      volumes:
        - name: app
          emptyDir: {}
        - name: cfg
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "common.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- range .Values.extraVolumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: Directory
        {{- end }}
{{- end -}}
