{{- include "common.deployment" (list . "jdownloader.deployment") -}}
{{- define "jdownloader.deployment" -}}
spec:
  template:
    spec:
      containers:
        - env:
            - name: MYJD_DEVICE_NAME
              value: {{ .Values.deviceName | default "Kubernetes" | quote }}
            - name: UMASK
              value: {{ .Values.umask | default "0002" | quote }}
            {{- if and .Values.myJdAccount.email .Values.myJdAccount.password }}
            - name: MYJD_USER
              value: {{ .Values.myJdAccount.email | quote }}
            - name: MYJD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.fullname" . }}
                  key: myJdAccount-password
            {{- end }}
          ports:
            - name: direct-conn
              containerPort: 3129
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/JDownloader/app
              name: app
            {{- if .Values.volumes.cfgPath }}
            - mountPath: /opt/JDownloader/app/cfg
              name: cfg
            {{- end }}
            {{- if .Values.volumes.downloadsPath }}
            - mountPath: /opt/JDownloader/Downloads
              name: downloads
            {{- end }}
          {{- include "common.container" . | nindent 10 }}
      volumes:
        - name: app
          emptyDir: {}
        {{- if .Values.volumes.cfgPath }}
        - name: cfg
          hostPath:
            path: {{ .Values.volumes.cfgPath }}
            type: Directory
        {{- end }}
        {{- if .Values.volumes.downloadsPath }}
        - name: downloads
          hostPath:
            path: {{ .Values.volumes.downloadsPath }}
            type: Directory
        {{- end }}
{{- end -}}
