{{- if .Values.myJdAccount.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  myJdAccount-password: {{ .Values.myJdAccount.password | b64enc | quote }}
{{- end }}
