{{- if .Values.myJdAccount.password -}}
{{- include "common.secret" (list . "jdownloader.secret") -}}
{{- end }}
{{- define "jdownloader.secret" -}}
data:
  myJdAccount-password: {{ .Values.myJdAccount.password | b64enc | quote }}
{{- end -}}
