{{- include "common.deployment" (list . "apprise.deployment") -}}
{{- define "apprise.deployment" -}}
spec:
  template:
    spec:
      containers:
        - env:
            - name: PUID
              value: "11319"
            - name: PGID
              value: "11319"
            - name: APPRISE_DEFAULT_THEME
              value: "dark"
            - name: APPRISE_STATEFUL_MODE
              value: "simple"
            - name: APPRISE_WORKER_COUNT
              value: {{ .Values.apprise.workerCount | quote }}
            {{- if .Values.apprise.configLock }}
            - name: APPRISE_CONFIG_LOCK
              value: "yes"
            {{- end }}
            {{- if .Values.apprise.adminMode }}
            - name: APPRISE_ADMIN
              value: "yes"
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 10

          volumeMounts:
            - name: data
              mountPath: /config
            - name: data
              mountPath: /plugin
            - name: data
              mountPath: /attach
            {{- if .Values.configSecretRef }}
            - name: config
              mountPath: /config/{{ .Values.configSecretRef.key }}
              subPath: {{ .Values.configSecretRef.key }}
            {{- end }}
            - name: tmp
              mountPath: /tmp
          {{- include "common.container" . | nindent 10 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "common.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.configSecretRef }}
        - name: config
          secret:
            secretName: {{ .Values.configSecretRef.name }}
            items:
              - key: {{ .Values.configSecretRef.key }}
                path: {{ .Values.configSecretRef.key }}
        {{- end }}
        - name: tmp
          emptyDir: {}
{{- end -}}
