resources:
  limits: null

database:
  hostname: cnpg-cluster-rw
  databaseName: test
  username: test
  passwordSecretName: test

extraVolumes:
  - name: data
    mountPath: /data
    hostPath: /tmp

machine-learning:
  resources:
    limits: null
