{{- include "common.deployment" (list . "blocky.deployment") -}}
{{- define "blocky.deployment" -}}
spec:
  template:
    spec:
      containers:
        - env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /app/blocky
                - healthcheck
          readinessProbe:
            exec:
              command:
                - /app/blocky
                - healthcheck
          startupProbe:
            exec:
              command:
                - /app/blocky
                - healthcheck
            initialDelaySeconds: 10
            failureThreshold: 15
          volumeMounts:
            - name: config
              mountPath: /app/config.yml
              subPath: config.yml
          {{- include "common.container" . | nindent 10 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "common.fullname" . }}
{{- end -}}
