{{- include "common.deployment" (list . "ntfy.deployment") -}}
{{- define "ntfy.deployment" -}}
spec:
  template:
    spec:
      containers:
        - args: ["serve"]
          env:
            - name: TZ
              value: {{ .Values.timezone | default "Europe/Berlin" | quote }}
            - name: NTFY_LISTEN_HTTP
              value: ":8080"
            - name: NTFY_CACHE_FILE
              value: "/var/cache/ntfy/cache.db"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/health
              port: http
          readinessProbe:
            httpGet:
              path: /v1/health
              port: http
          volumeMounts:
            - name: config
              mountPath: /etc/ntfy/server.yml
              subPath: server.yml
            - name: cache
              mountPath: /var/cache/ntfy
          {{- include "common.container" . | nindent 10 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "common.fullname" . }}
        - name: cache
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "common.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end -}}
