replicaCount: 1

image:
  repository: caronc/apprise
  pullPolicy: IfNotPresent
  tag: "edge"  # Defaults to chart appVersion

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 11319
  runAsGroup: 11319
  fsGroup: 11319

securityContext:
  runAsNonRoot: true
  runAsUser: 11319

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: apprise.192-168-178-31.sslip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "1000m"

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  annotations: {}
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 250Mi

serviceMonitor:
  enabled: true

workerCount: ""  # Defaults to '1'

configSecretRef: {}
