replicaCount: 1

image:
  repository: ghcr.io/caronc/apprise
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to chart appVersion

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 11319
  runAsGroup: 11319
  fsGroup: 11319
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: apprise.192-168-178-31.sslip.io

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "1000m"

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  annotations: {}
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 250Mi

timezone: "Europe/Berlin"

serviceMonitor:
  enabled: true

configSecretRef: {}

apprise:
  configLock: true
  adminMode: true
  workerCount: 1

bridge:
  enabled: true

signal:
  enabled: true
