{{- include "common.deployment" (list . "gotify.deployment") -}}
{{- define "gotify.deployment" -}}
spec:
  template:
    spec:
      enableServiceLinks: false
      containers:
        - env:
            - name: TZ
              value: {{ .Values.timezone | default "Europe/Berlin" | quote }}
            - name: GOTIFY_SERVER_PORT
              value: "8080"
            {{- if .Values.defaultUser.name }}
            - name: GOTIFY_DEFAULTUSER_NAME
              value: {{ .Values.defaultUser.name | quote }}
            {{- end }}
            {{- if .Values.defaultUser.pass }}
            - name: GOTIFY_DEFAULTUSER_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.fullname" . }}
                  key: defaultuser-pass
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- if .Values.volumes.dataPath }}
          volumeMounts:
            - mountPath: /app/data
              name: data
          {{- end }}
          {{- include "common.container" . | nindent 10 }}
      {{- if .Values.volumes.dataPath }}
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.volumes.dataPath }}
            type: Directory
      {{- end }}
{{- end -}}
