apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gotify.fullname" . }}
  labels:
    {{- include "gotify.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gotify.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gotify.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if or .Values.defaultUser .Values.timezone }}
          env:
            {{- if .Values.defaultUser.name }}
            - name: GOTIFY_DEFAULTUSER_NAME
              value: {{ .Values.defaultUser.name | quote }}
            {{- end }}
            {{- if .Values.defaultUser.pass }}
            - name: GOTIFY_DEFAULTUSER_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "gotify.fullname" . }}
                  key: defaultuser-pass
            {{- end }}
            {{- if .Values.timezone }}
            - name: TZ
              value: {{ .Values.timezone | quote }}
            {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
