apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gotify.fullname" . }}
  labels:
    {{- include "gotify.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gotify.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gotify.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: TZ
              value: {{ .Values.timezone | default "Europe/Berlin" | quote }}
            - name: GOTIFY_SERVER_PORT
              value: "8080"
            {{- if .Values.defaultUser.name }}
            - name: GOTIFY_DEFAULTUSER_NAME
              value: {{ .Values.defaultUser.name | quote }}
            {{- end }}
            {{- if .Values.defaultUser.pass }}
            - name: GOTIFY_DEFAULTUSER_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "gotify.fullname" . }}
                  key: defaultuser-pass
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.volumes.dataPath }}
          volumeMounts:
            - mountPath: /app/data
              name: data
          {{- end }}
      {{- if .Values.volumes.dataPath }}
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.volumes.dataPath }}
            type: Directory
      {{- end }}
