{{- if .Values.defaultUser.pass -}}
{{- include "common.secret" (list . "gotify.secret") -}}
{{- end }}
{{- define "gotify.secret" -}}
data:
  defaultuser-pass: {{ .Values.defaultUser.pass | b64enc | quote }}
{{- end -}}
