{{- if .Values.defaultUser.pass -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gotify.fullname" . }}
  labels:
    {{- include "gotify.labels" . | nindent 4 }}
type: Opaque
data:
  defaultuser-pass: {{ .Values.defaultUser.pass | b64enc | quote }}
{{- end }}
