{{- include "common.configmap" (list . "filebrowser.configmap") -}}
{{- define "filebrowser.configmap" -}}
data:
  .filebrowser.json: |
    {{- .Values.config | toPrettyJson | nindent 4 }}
{{- end -}}
