{{- include "common.deployment" (list . "filebrowser.deployment") -}}
{{- define "filebrowser.deployment" -}}
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - name: config
              mountPath: /.filebrowser.json
              subPath: .filebrowser.json
            - name: database
              mountPath: /database
            {{- range .Values.extraVolumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly | default false }}
            {{- end }}
          {{- include "common.container" . | nindent 10 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "common.fullname" . }}
        - name: database
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "common.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- range .Values.extraVolumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: Directory
        {{- end }}
{{- end -}}
