{{- include "common.deployment" (list . "filebrowser.deployment") -}}
{{- define "filebrowser.deployment" -}}
spec:
  template:
    spec:
      containers:
        - ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - name: config
              mountPath: /.filebrowser.json
              subPath: .filebrowser.json
            {{- if .Values.volumes.databasePath }}
            - name: database
              mountPath: /database
            {{- end }}
            {{- if .Values.volumes.rootDir }}
            - name: root-dir
              mountPath: {{ .Values.config.root }}
            {{- end }}
          {{- include "common.container" . | nindent 10 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "common.fullname" . }}
        {{- if .Values.volumes.databasePath }}
        - name: database
          hostPath:
            path: {{ .Values.volumes.databasePath }}
            type: Directory
        {{- end }}
        {{- if .Values.volumes.rootDir }}
        - name: root-dir
          hostPath:
            path: {{ .Values.volumes.rootDir }}
            type: Directory
        {{- end }}
{{- end -}}
