immich:
  controllers:
    main:
      containers:
        main:
          image:
            # TODO
            # renovate: image=ghcr.io/immich-app/immich-server
            tag: v2.4.1
          env:
            TZ: "Europe/Berlin"
            DB_HOSTNAME: cnpg-cluster-rw.cnpg-system.svc.cluster.local
            DB_PORT: 5432
            DB_DATABASE_NAME: immich
            DB_USERNAME: immich
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: password

  immich:
    persistence:
      library:
        existingClaim: immich-library
    configuration:
      storageTemplate:
        enabled: true
        template: "{{y}}/{{y}}-{{MM}}/{{filename}}"

  valkey:
    enabled: true

  server:
    ingress:
      main:
        enabled: true

  machine-learning:
    persistence:
      cache:
        type: emptyDir  # TODO: Set this to persistentVolumeClaim
        # storageClass: TODO

persistence:
  accessModes:
    - ReadWriteOnce
  size: 500Mi
