apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-ionos-staging
spec:
  acme:
    email: change-me@example.net
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-ionos-staging-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.egvimo
            solverName: ionos
            config:
              apiUrl: https://api.hosting.ionos.com/dns/v1
              publicKeySecretRef:
                name: ionos-api-key
                key: public-prefix
              secretKeySecretRef:
                name: ionos-api-key
                key: secret
