apiVersion: v2
name: kibitzr
description: Personal Web Assistant
type: application
version: 0.1.0
appVersion: "v7.0.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
