{{- include "common.deployment" (list . "home-assistant.deployment") -}}
{{- define "home-assistant.deployment" -}}
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - env:
            - name: TZ
              value: {{ .Values.timezone | default "Europe/Berlin" | quote }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /manifest.json
              port: http
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /manifest.json
              port: http
            initialDelaySeconds: 5
          volumeMounts:
            - name: config
              mountPath: /config
            - name: configuration
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
          {{- include "common.container" . | nindent 10 }}
      initContainers:
        - name: ensure-config
          image: busybox
          command:
            - sh
            - -c
            - |
              set -eux
              # Check if the automations file exists
              if [ ! -f /config/automations.yaml ]; then
                echo "Automations file not found, creating a new one"
                touch /config/automations.yaml
                echo "[]" >> /config/automations.yaml
              fi
              # Check if the scripts file exists
              if [ ! -f /config/scripts.yaml ]; then
                echo "Scripts file not found, creating a new one"
                touch /config/scripts.yaml
              fi
              # Check if the scenes file exists
              if [ ! -f /config/scenes.yaml ]; then
                echo "Scenes file not found, creating a new one"
                touch /config/scenes.yaml
              fi
          volumeMounts:
            - name: config
              mountPath: /config
      hostNetwork: true
      volumes:
        - name: config
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "common.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: configuration
          configMap:
            name: {{ include "common.fullname" . }}
        {{- if .Values.notifiersSecretRef }}
        - name: notifiers
          secret:
            secretName: {{ .Values.notifiersSecretRef.name }}
            items:
              - key: {{ .Values.notifiersSecretRef.key }}
                path: {{ .Values.notifiersSecretRef.key }}
        {{- end }}
        {{- if .Values.restCommandsSecretRef }}
        - name: restCommands
          secret:
            secretName: {{ .Values.restCommandsSecretRef.name }}
            items:
              - key: {{ .Values.restCommandsSecretRef.key }}
                path: {{ .Values.restCommandsSecretRef.key }}
        {{- end }}
{{- end -}}
