{{- if .Values.ingress.enabled }}
{{- $fullName := include "common.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: {{ .Values.service.name | default "http" }}
          {{- if .Values.matterServer.enabled }}
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: matter
          {{- end }}
{{- end }}
