apiVersion: v2
name: home-assistant
type: application
version: 0.1.15
# renovate: image=ghcr.io/home-assistant/home-assistant
appVersion: "2026.4.4"
dependencies:
  - name: common
    version: 0.1.5
    repository: oci://ghcr.io/egvimo/charts
