replicaCount: 1

image:
  repository: ghcr.io/dani-garcia/vaultwarden
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to chart appVersion

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 11319
  runAsGroup: 11319
  fsGroup: 11319
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: vaultwarden.192-168-178-31.sslip.io

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "1Gi"
    cpu: "1500m"

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  annotations: {}
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

extraEnv: []

vaultwarden:
  databaseUrlSecretRef:
    name: vaultwarden
    key: databaseUrl
  adminTokenSecretRef:
    name: vaultwarden
    key: adminToken
  signupsAllowed: false
  websocketEnabled: true
