{{- include "common.deployment" (list . "whoami.deployment") -}}
{{- define "whoami.deployment" -}}
spec:
  template:
    spec:
      containers:
        - env:
            - name: WHOAMI_PORT_NUMBER
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 1
          {{- include "common.container" . | nindent 10 }}
{{- end -}}
