apiVersion: v2
name: firefox
type: application
version: 0.1.0
# renovate: image=ghcr.io/jlesage/firefox
appVersion: "v26.03.1"
dependencies:
  - name: common
    version: 0.1.5
    repository: oci://ghcr.io/egvimo/charts
