image:
  repository: ghcr.io/jlesage/firefox
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to chart appVersion

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 11319
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
    add:
      - SETUID
      - SETGID
      - CHOWN
      - FOWNER
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
      - KILL
  privileged: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: firefox.192-168-178-31.sslip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  requests:
    memory: "512Mi"
    cpu: "100m"
  limits:
    memory: "2048Mi"
    cpu: "3000m"

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  annotations: {}
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 500Mi

timezone: "Europe/Berlin"

downloadsVolume:
  hostPath: /tmp
